services:
  redis:
    image: redis:7
    container_name: user-service-redis
    restart: always
    ports:
      - "6400:6379"
    volumes:
      - user-service-redis-data:/data

  user-service-db:
    image: postgres:17
    container_name: user-service-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user-service
    volumes:
      - user-service-db-data:/var/lib/postgresql/data

volumes:
  user-service-db-data:
  user-service-redis-data: